---
- name: "edit the name of the host"
  hostname: 
    name: "{{ inventory_hostname }}"
  when: edit_hostname == "yes"

- name: Download Install docker script
  template:
    src: "install_docker.sh.j2"
    dest: "/home/{{ ansible_user }}/install_docker.sh"

- name: run script to install docker
  command: "sh /home/{{ ansible_user }}/install_docker.sh"
  when: ansible_docker0 is undefined

- name: start service docker
  service:
    name: docker
    state: started
    enabled: yes

- name: give the privilège to user
  user:
    name: {{ ansible_user }}
    append: yes
    groups:
      - docker
  when: ansible_user is defined

- name: install python pip for ubuntu
  package:
    name: python3-pip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install python pip for Kali
  command: "sudo apt install python3-pip -y"
  when: ansible_distribution == "Kali"

- name: download pip script for centos
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py
  when: ansible_distribution == "CentOS"

- name: install python-pip for centos
  command: python2.7 /tmp/get-pip.py
  when: ansible_distribution == "CentOS"

- name: install docker-py module
  pip:
    name: docker-py
    state: present

